!title: Sachertorte
!size: eine 28 cm Springform
!author: Andreas Wallner
!source: Werner Ganster
!lang: de

# 130g Süßrahmbutter, weich
# 110g Staubzucker
# 1/2 Schote Vanillemark
* cremig rühren

# 130g Mehl
* über die Buttermasse sieben

# 130g Manner Schokolade
* über Wasserbad schmelzen

# 6 Eidotter
* einzeln zu Buttermasse zugeben
* Schokolade unter die Masse mischen

# 6 Eiklar
# 110g Kristallzucker
* Eier steif schlagen
* Zucker einrießeln lassen, schnittfest schlagen
* Schnee und Mehl unter die Buttermasse heben

+ im auf 170°C vorgeheizten Rohr ca. 1h backen, die ersten 15 Minuten Backrohr einen Spalt offen lassen. Fertiggebacken wenn die Torte einen leichten Fingerdruck sanft erwiedert.

* in der Springform auf ein Gitter stürzen, 20 Minuten auskühlen lassen
* umdrehen, Springform entfernen, vollständig auskühlen lassen

# 1Glas Marillenmarmelade
* Torte durchschneiden, mit Marmelade füllen
* Seite und Deckel mit Marmelade bestreichen

# 150g Manner Schokolade
* über Wasserbad schmelzen

# 200g Zucker
# 1/8l Wasser
* aufkochen, 5 Minuten kochen
* etwas erkalten lassen
* Schokolade unterrühren
* auskühlen lassen bis zähflüssig
* Torte glasieren